### ISSUE TITLE
mpu9250 compatibility

### ISSUE THREAD

**Issue by mahmoudkamelibrahim** [vmayoral/bb_mpu9150#3]
Is This package compatible with mpu9250 (sparkfun SEN-13762) ?

**Comment by vmayoral** [comment]
Hi @ma7moudk, unfortunately i don't have that hardware to try it myself but both sensors (the MPU9250 and the MPU9150) share many aspects (register-wise) so I'd expect a smooth port in case it does not work out of the box.

Please report back if you give it a try.

**Comment by vmayoral** [comment]
Closing this for now.

**Comment by imakr** [comment]
@vmayoral Hello victor,
Thanks for your linux project. I would like to port and test this project for my MPU9250 board. 
Before i would take it up, i would like to get the below clarification from your work with MPU9150.
In one of my project with Motion Driver 6.12 & MPU9250, i was able to observe the Quaternion Qz drifts over time. Did you observe such a behviour with 9150 ? Is there something im missing out with 9250. Im a newbie with motion tracking sensors.
